version: '3.4'
name: codeflix
services:
  db:
    container_name: catalogdb
    hostname: ctalogdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: codeflix
networks:
  default:
    name: codeflix
