apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: codeflix
spec:
  type: NodePort
  selector:
    app: mysql-deploy
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32006